# Tasks

These are my solutions to the tasks. The author is Mateusz Pawlowski.
***

## Task 1: Calculate a sqaure root

### Introduction
[1] In a mathematical form, a square root is a number equal to a number that is squared by itself. For example: $ y^2 = x $. 
<br>
The symbol $ \sqrt{} $ will always mean the positive square root.
<br>
Example: $ \sqrt{64} = 8 $ thats beacause $ 8^2 = 64 $

We can calculate the square root of a number using Newton's method [1,2].
To find the square root $z$ number $x$, we can iterate using the following equation.
$$ z = y + (\frac xy) $$

### My way of getting the answer
With a quick google search I was able to find some good square root function however all of the functions were outputting around 50 digits after the decimal and after that it would just show me zeros. That was no good to me as our task stated we needed the first hundred numbers after the decimal. This made the task much harder to figure out and gave me a challenge. After some resaearch I found a forum on stackoverflow [4], explaining and showing a way of generating x amount of digits. This would store the information in a string. Now after that I have the numbers itself and they are fairly accurate to the original i needed to add a decimal after the first digit. That is when I started looking around the internet again and found another forum on stackoverflow explaining and showing how to go about it [5].

### References
[1] Wikipedia; Square root; https://en.wikipedia.org/wiki/Square_root

[2] A Tour of Go; Exercise: Loops and Functions; https://tour.golang.org/flowcontrol/8

[3] Newton's Method; https://en.wikipedia.org/wiki/Newton%27s_method

[4] Generate x Amount of digits: Author, cashev; https://stackoverflow.com/questions/5187664/generating-digits-of-square-root-of-2

[5] Add dot seperator: Author, Dmytro Chasovskyi; https://stackoverflow.com/questions/53976250/how-to-add-dot-separator-on-different-positions-of-a-number-in-python

In [1]:
def sqrt2():
    
    """
    A function to calculate the square root of a number x.
    """
    
    # initialise x to 2 as we are 
    # looking for the square root of 2
    x = 2
    
    x = x *(10**(2*100))
    y = 0
    z = 1 * (10**100)
    
    # while loop until the accuracy is good
    while y!=z:
        y = z
        z = (y + ( x // y)) >> 1
        
    # store the value in a list
    l = list(str(z))
    
    # add a dot after 1 decimanl place
    l.insert(1, '.')
    
    # in order to make the numbers horizontal
    # instead of vertical
    num = ''.join(l)
    
    # return the value
    return num

In [2]:
# call function
sqrt2()

'1.4142135623730950488016887242096980785696718753769480731766797379907324784621070388503875343276415727'

https://www.tutorialspoint.com/How-to-perform-square-root-without-using-math-module-in-Python

https://www.codegrepper.com/code-examples/matlab/Limiting+floats+to+100+decimal+points+python

https://apod.nasa.gov/htmltest/gifcity/sqrt10.1mil

## Task: Chi squared value


### Introduction
A Chi Squared test also known as $ x^2 $ test is a statistical hypothesis test. It is a test to see is there a significant relationship between two categorical variables (wheter the varaibles are independent or related). This test can not compare any continuous variables or categorical and continuous  variables. 

We are not calculating one thing with the whole test. Matter of fact it is 4 different tests we are going to perform. The degrees of freedom, expected frequencies, test statistics and the p-value.
Here are the formulas for each one:

[2]
**Degrees of freedom:** $DF = (r - 1) * (c - 1)$ where $r$ is the number of level for one categorical variable and $c$ is the number of levels for the other categorical variables.

[2]
**Expected frequencies:** $E_r,_c = \frac{n_r*n_c}{n}$ (to see it better: $E_r,_c = n_r*n_c / n$) where $E_r,_c$ is the expected frequency count for level $r$ of variable $A$ and level $c$ of variable $B$. $N_r$ is the total number of sample observations at level $r$ of variable $A$. $N_c$ is the total number of sample observations at level $c$ of Variable $B$. $n$ is the total sample size.

[2]
**Test Statistic:** $x^2 = \Sigma [\frac{(O_r,_c - E_r,_c)^2}{E_r,_c}]$ (to see it better: $x^2 = \Sigma [(O_r,_c - E_r,_c)^2 / E_r,_c])$ where $O_r,_c$ is the observed frequency count at level $r$ of Variable $A$ and level $c$ of Variable $B$, and $E_r,_c$ is the expected frequency count at level $r$ of Variable $A$ and level $c$ of Variable $B$.

[2]
**P Value:** The P-value is the probability of observing a sample statistic as extreme as the test statistic. Since the test statistic is a chi-square, use the Chi-Square Distribution Calculator to assess the probability associated with the test statistic. Use the degrees of freedom computed above.

### My Way Of Getting The Answer
For this task we were given a table that was originally taken from the wikipedia. It is shown with the image below.
![Chi Squared](img/chiSquare.png)
I had no idea of what a chi square test for independace was before starting this task. This made me have to do much more research compared to the square root task. I had a hard time in the beginning figuring it out but after some time I found a nice sites that helped me understand it better. With me understanding it, I started to look at the coding part. I there was lots of documentation but eventually I found a website 
### References
https://libguides.library.kent.edu/spss/chisquare

[2] Stat Trek: Analyze Sample Data;https://stattrek.com/chi-square-test/independence.aspx
https://oeis.org/wiki/List_of_LaTeX_mathematical_symbols

https://pythonhealthcare.org/2018/04/13/58-statistics-chi-squared-test/

In [3]:
# imports
import scipy.stats as stats

# creating arrays 
cols = ['A', 'B', 'C', 'D']
data = [[90, 60, 104, 95],[30,50,51,20],[30,40,45,35]]

# chi2 - chi squared value
# p - associated p value
# df - degrees freedom
# exp - expected frequencies

# is a function that returns 4 values
chi2,p,df,exp = stats.chi2_contingency(data)

# print outs of the answers
print("%.1f"% chi2)
print(p)
print(df)
print(exp)

24.6
0.0004098425861096696
6
[[ 80.53846154  80.53846154 107.38461538  80.53846154]
 [ 34.84615385  34.84615385  46.46153846  34.84615385]
 [ 34.61538462  34.61538462  46.15384615  34.61538462]]


### Task 3: Standard Deviation Difference

Population standard deviation defenition:Population standard deviation is a paramete. It is a fixed value calculated from every individual from the population. 

Sample standard devation defenition: Sample standard deviation is a statistic. It is calculated only from a "sample" of the population. Since it depends on the sample itself it has a higher variability making it greater from population standard devitation 


https://www.thoughtco.com/population-vs-sample-standard-deviations-3126372#:~:text=The%20population%20standard%20deviation%20is,the%20individuals%20in%20a%20population.





In [4]:
# imports
import numpy as np 

# datasets for calculations
fullData = [28, 20, 36, 41, 45, 66, 15, 42, 98, 2 , 5 , 7 , 11, 23]
sampleData = [2, 11, 36 , 41, 66]

# calculating the std.P with full data
stdP = np.sqrt(np.sum((fullData - np.mean(fullData))**2)/len(fullData))

# using sample data to calculate std.P and std.S
stdQS = np.sqrt(np.sum((sampleData - np.mean(sampleData))**2)/len(sampleData))
stdS = np.sqrt(np.sum((sampleData - np.mean(sampleData))**2)/len(sampleData)-1)

# printing out and showing that std.S is more accurate from std.P
print("Population Standard Deviation:",stdP,"\n")
print("Sample Standard Deviation:",stdQS)
print("Sample Standard Deviation:",stdS)


Population Standard Deviation: 25.491194958419722 

Sample Standard Deviation: 22.76312808029687
Sample Standard Deviation: 22.741152125607


### Task4: Iris Data Set 