# Tasks

These are my solutions to the tasks. The author is Mateusz Pawlowski.
***

### Task 1: Calculate a sqaure root

[1] In a mathematical form, a square root is a number equal to a number that is squared by itself. For example: $ y^2 = x $

We can calculate the square root of a number using Newton's method [1,2].
To find the square root $z$ number $x$, we can iterate using the following equation.
$$ z = y + (\frac xy) $$

[1] Wikipedia; Square root; https://en.wikipedia.org/wiki/Square_root

[2] A Tour of Go; Exercise: Loops and Functions; https://tour.golang.org/flowcontrol/8

[3] Newton's Method; https://en.wikipedia.org/wiki/Newton%27s_method



https://stackoverflow.com/questions/5187664/generating-digits-of-square-root-of-2

https://stackoverflow.com/questions/53976250/how-to-add-dot-separator-on-different-positions-of-a-number-in-python

In [1]:
def sqrt2():
    
    """
    A function to calculate the square root of a number x.
    """
    
    # initialise x to 2 as we are 
    # looking for the square root of 2
    x = 2
    
    x = x *(10**(2*100))
    y = 0
    z = 1 * (10**100)
    
    # while loop until the accuracy is good
    while y!=z:
        y = z
        z = (y + ( x // y)) >> 1
        
    # store the value in a list
    l = list(str(z))
    
    # add a dot after 1 decimanl place
    l.insert(1, '.')
    
    # in order to make the numbers horizontal
    # instead of vertical
    num = ''.join(l)
    
    # return the value
    return num

In [2]:
# call function
sqrt2()

'1.4142135623730950488016887242096980785696718753769480731766797379907324784621070388503875343276415727'

https://www.tutorialspoint.com/How-to-perform-square-root-without-using-math-module-in-Python

https://www.codegrepper.com/code-examples/matlab/Limiting+floats+to+100+decimal+points+python

https://apod.nasa.gov/htmltest/gifcity/sqrt10.1mil

### Task: Chi squared value


In [3]:
# imports
import scipy.stats as stats

# creating arrays 
cols = ['A', 'B', 'C', 'D']
data = [[90, 60, 104, 95],[30,50,51,20],[30,40,45,35]]

# chi2 - chi squared value
# p - associated p value
# d - degrees freedom
# exp - expected frequencies
chi2,p,df,exp = stats.chi2_contingency(data)

# print outs of the answers
print("%.1f"% chi2)
print(p)
print(df)
print(exp)

24.6
0.0004098425861096696
6
[[ 80.53846154  80.53846154 107.38461538  80.53846154]
 [ 34.84615385  34.84615385  46.46153846  34.84615385]
 [ 34.61538462  34.61538462  46.15384615  34.61538462]]


### Task 3: Standard Deviation Difference

Population standard deviation defenition:Population standard deviation is a paramete. It is a fixed value calculated from every individual from the population. 

Sample standard devation defenition: Sample standard deviation is a statistic. It is calculated only from a "sample" of the population. Since it depends on the sample itself it has a higher variability making it greater from population standard devitation 


https://www.thoughtco.com/population-vs-sample-standard-deviations-3126372#:~:text=The%20population%20standard%20deviation%20is,the%20individuals%20in%20a%20population.





In [20]:
import numpy as np 

data = [28, 20, 36, 41, 45, 66, 15, 42, 98]

stdP = np.sqrt(np.sum((data - np.mean(data))**2)/len(data)) 
stdS = np.sqrt(np.sum((data - np.mean(data))**2)/len(data)-1)

print("Population Standard Deviation:",stdP,"\n")
print("Sample Standard Deviation:",stdS)


Population Standard Deviation: 23.917037679403876 

Sample Standard Deviation: 23.896122935698685


### Task4: Iris Data Set 

In [ ]:
# IDS